# Generated by Django 5.2.17 on 2026-08-16 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedRing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_ids', models.JSONField(default=list)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('risk_score', models.FloatField(default=0.0)),
                ('explanation', models.JSONField(default=list)),
                ('total_cycle_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('invoice_ids', models.JSONField(default=list)),
                ('officer_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-risk_score', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LedgerBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(unique=True)),
                ('timestamp', models.DateTimeField()),
                ('payload', models.JSONField(default=dict)),
                ('previous_hash', models.CharField(max_length=64)),
                ('hash', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('feature_snapshot', models.JSONField(default=dict)),
                ('explanation', models.JSONField(default=list)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='core.company')),
            ],
            options={
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['company', '-computed_at'], name='fraud_engin_company_afcf7b_idx')],
            },
        ),
    ]
