# Generated by Django 5.2.17 on 2026-08-25 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_company_gstin_dataset_company_dataset_and_more'),
        ('fraud_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flaggedring',
            name='closure',
            field=models.CharField(choices=[('invoice', 'Closed by invoice'), ('control', 'Closed by shared ownership')], default='invoice', max_length=16),
        ),
        migrations.AddField(
            model_name='flaggedring',
            name='dismissal_reason',
            field=models.CharField(blank=True, choices=[('genuine_trade', 'Genuine two-way trade'), ('not_circular', 'Shell company, but not a circular ring'), ('already_open', 'Already under investigation'), ('insufficient', 'Insufficient evidence to act'), ('data_quality', 'Data quality problem, not fraud'), ('other', 'Other (see note)')], max_length=32),
        ),
        migrations.AddField(
            model_name='flaggedring',
            name='evidence',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='flaggedring',
            name='kind',
            field=models.CharField(choices=[('ring', 'Circular trade ring'), ('mill', 'Fake invoice mill')], default='ring', max_length=16),
        ),
        migrations.AddField(
            model_name='flaggedring',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='flaggedring',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flaggedring',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_rings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flaggedring',
            name='status',
            field=models.CharField(choices=[('pending', 'Awaiting review'), ('confirmed', 'Confirmed fraudulent'), ('dismissed', 'Dismissed - not fraud')], db_index=True, default='pending', max_length=16),
        ),
        migrations.CreateModel(
            name='DetectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('model_version', models.CharField(blank=True, max_length=64)),
                ('model_trained_at', models.CharField(blank=True, max_length=32)),
                ('risk_threshold', models.FloatField(default=70.0)),
                ('companies_scored', models.PositiveIntegerField(default=0)),
                ('rings_detected', models.PositiveIntegerField(default=0)),
                ('mills_detected', models.PositiveIntegerField(default=0)),
                ('high_risk_count', models.PositiveIntegerField(default=0)),
                ('total_value_at_risk', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_runs', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.dataset')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('html', models.TextField(blank=True)),
                ('summary', models.JSONField(default=dict)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('recipients', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Generated, not sent'), ('sent', 'Sent'), ('failed', 'Send failed')], default='draft', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_reports', to=settings.AUTH_USER_MODEL)),
                ('ledger_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='fraud_engine.ledgerblock')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='fraud_engine.detectionrun')),
            ],
            options={
                'ordering': ['-generated_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='flaggedring',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rings', to='fraud_engine.detectionrun'),
        ),
        migrations.AddField(
            model_name='riskscore',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='fraud_engine.detectionrun'),
        ),
        migrations.AddIndex(
            model_name='flaggedring',
            index=models.Index(fields=['run', '-risk_score'], name='fraud_engin_run_id_96bde6_idx'),
        ),
        migrations.AddIndex(
            model_name='riskscore',
            index=models.Index(fields=['run'], name='fraud_engin_run_id_80504d_idx'),
        ),
    ]
