# Generated by Django 5.2.17 on 2026-08-27 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_create_role_groups'),
        ('fraud_engine', '0003_adopt_existing_alerts_into_a_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='casereport',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_reports', to='core.company'),
        ),
        migrations.AddField(
            model_name='casereport',
            name='report_type',
            field=models.CharField(choices=[('run', 'Detection run'), ('company', 'Single company')], default='run', max_length=16),
        ),
        migrations.AlterField(
            model_name='casereport',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='fraud_engine.detectionrun'),
        ),
    ]
