# Generated by Django 5.2.17 on 2026-08-16 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(db_index=True, max_length=15, unique=True)),
                ('pan', models.CharField(db_index=True, max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('director_name', models.CharField(db_index=True, max_length=255)),
                ('registered_address', models.CharField(db_index=True, max_length=500)),
                ('registered_date', models.DateField()),
                ('declared_turnover', models.DecimalField(decimal_places=2, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('date', models.DateField(db_index=True)),
                ('goods_description', models.CharField(max_length=255)),
                ('has_eway_bill', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoices', to='core.company')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoices', to='core.company')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['seller', 'buyer'], name='core_invoic_seller__757b38_idx')],
            },
        ),
    ]
